---
- name: Encrypt .env files
  hosts: localhost
  gather_facts: no
  vars:
    update_env: true

  tasks:
    - name: Find .env files

        recurse: yes 
        patterns: "*.env.vault"
      register: env_files

    - name: Encrypt .env files
      ansible.builtin.shell: |
        for vault_file in "{{ item.path }}" ; do
          decrypted_file="${vault_file%.vault}"
          ansible-vault decrypt "$vault_file" --output "$decrypted_file" --vault-password-file vault_password.sh
        done
        #      ansible.builtin.command: ansible-vault decrypt "{{ item.path }}" --output= "{{ item.path | basename }}" --vault-password-file vault_password.sh
      loop: "{{ env_files.files }}"
      when: item.isreg and update_env == true
